# Generated by Django 5.1.6 on 2025-02-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest_be', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='website_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('analyzed', 'Analyzed'), ('email_generated', 'Email Generated'), ('email_sent', 'Email Sent'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
