# Generated by Django 5.1.6 on 2025-02-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest_be', '0002_lead_ai_analysis_lead_website_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='website_metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
