# Generated by Django 5.1.6 on 2025-02-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest_be', '0005_rename_user_id_lead_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='user',
            new_name='user_id',
        ),
    ]
